"""add income table

Revision ID: 0e28591a36ed
Revises: fa3efb9fe861
Create Date: 2025-07-25 01:10:06.096898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e28591a36ed'
down_revision: Union[str, Sequence[str], None] = 'fa3efb9fe861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.alter_column('expenses', 'category',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('expenses', 'expense_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_date', sa.DATE(), nullable=False))
    op.alter_column('expenses', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('expenses', 'category',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_table('incomes')
    # ### end Alembic commands ###
