"""add monthly_summaries table

Revision ID: 48df61e5957b
Revises: 0bff410969fc
Create Date: 2025-07-29 21:06:50.702470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48df61e5957b'
down_revision: Union[str, Sequence[str], None] = '0bff410969fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_summaries_id'), 'monthly_summaries', ['id'], unique=False)
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.alter_column('expenses', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('expenses', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    op.drop_column('expenses', 'account_id')
    op.alter_column('incomes', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'incomes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.alter_column('incomes', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('expenses', sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.alter_column('expenses', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_table('accounts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.ENUM('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'CASH', 'OTHER'), nullable=False),
    sa.Column('balance', mysql.FLOAT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('accounts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.drop_index(op.f('ix_monthly_summaries_id'), table_name='monthly_summaries')
    op.drop_table('monthly_summaries')
    # ### end Alembic commands ###
