"""add_date_fields_to_expenses_and_incomes

Revision ID: f7f050117e17
Revises: 0e28591a36ed
Create Date: 2025-07-25 18:17:44.222638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f050117e17'
down_revision: Union[str, Sequence[str], None] = '0e28591a36ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable date columns first
    op.add_column('expenses', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('incomes', sa.Column('date', sa.DateTime(), nullable=True))
    
    # Update existing records with current timestamp
    op.execute("UPDATE expenses SET date = NOW() WHERE date IS NULL")
    op.execute("UPDATE incomes SET date = expense_date WHERE date IS NULL")
    
    # Make columns not nullable
    op.alter_column('expenses', 'date', existing_type=sa.DateTime(), nullable=False)
    op.alter_column('incomes', 'date', existing_type=sa.DateTime(), nullable=False)
    
    # Drop old column
    op.drop_column('incomes', 'expense_date')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('expense_date', sa.DATE(), nullable=False))
    op.drop_column('incomes', 'date')
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###
